export const imgArrData = [
    {
        'src':'static/s1.jpg',
        id:1,
    },
    {
        'src':'static/s2.jpg',
        id:2,
    },
    {
        'src':'static/s3.jpg',
        id:3,
    },
    {
        'src':'static/s4.jpg',
        id:4,
    },
    {
        'src':'static/s5.jpg',
        id:5,
    },{
        'src':'static/s6.jpg',
        id:6,
    },
    {
        'src':'static/s7.jpg',
        id:7,
    },
    {
        'src':'static/s8.jpg',
        id:8,
    },
    {
        'src':'static/s9.jpg',
        id:9,
    },
    {
        'src':'static/s10.jpg',
        id:10,
    },
    {
        'src':'https://picsum.photos/200/300',
        id:11,
    },
    {
        'src':'https://picsum.photos/1200/2300',
        id:12,
    },
    {
        'src':'static/s1.jpg',
        id:13,
    },
    {
        'src':'static/s2.jpg',
        id:14,
    },
    {
        'src':'static/s3.jpg',
        id:15,
    },
    {
        'src':'static/s4.jpg',
        id:16,
    },
    {
        'src':'static/s5.jpg',
        id:17,
    },{
        'src':'static/s6.jpg',
        id:18,
    },
    {
        'src':'static/s7.jpg',
        id:19,
    },
    {
        'src':'static/s8.jpg',
        id:20,
    },
    {
        'src':'static/s9.jpg',
        id:21,
    },
    {
        'src':'static/s10.jpg',
        id:22,
    },
    {
        'src':'https://picsum.photos/200/300',
        id:23,
    },
    {
        'src':'https://picsum.photos/1200/2300',
        id:24,
    },
    {
        'src':'https://picsum.photos/1200/2300',
        id:25,
    },
];